Repository mfts/papermark, pull requests merged in 2024-10, with the labels that each got.

#632 Fixed issues with inconsistent theming in various components
  components/billing/upgrade-plan-modal.tsx
  package-lock.json
  pages/settings/upgrade.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#639 feat:adding side quest tracking file
  oss-gg/oss-gg-quests/1-record-your-first-user-experience.md
Labels: 🕹️ oss.gg, 🕹️ 300 points

#608 599-Add custome favicon icon in document link
  app/favicon.ico
  components/links/link-sheet/index.tsx
  components/links/link-sheet/og-section.tsx
  components/links/links-table.tsx
  components/settings/og-preview.tsx
  components/view/custom-metatag.tsx
  lib/utils.ts
  lib/utils/resize-image.ts
  pages/_app.tsx
  pages/api/file/logo-upload.ts
  pages/api/links/[id]/dataroom.ts
  pages/api/links/[id]/index.ts
  pages/api/links/domains/[...domainSlug].ts
  pages/api/links/index.ts
  pages/api/teams/[teamId]/presets/index.ts
  pages/settings/presets.tsx
  pages/view/[linkId]/index.tsx
  pages/view/domains/[domain]/[slug]/index.tsx
  prisma/migrations/20241004024010_add_favicon_column/migration.sql
  prisma/schema.prisma
Labels: 🕹️ oss.gg, 🕹️ 750 points

#613 Fix/made the dataroom route protected in case user hasn't opted for any trial or plan
  pages/datarooms/index.tsx
Labels: 🕹️ oss.gg, 🕹️ 150 points

#642 ossgg: adding side quest tracking file
  oss-gg/1-meme-magic.md
  oss-gg/2-gif-magic.md
  oss-gg/3-follow-linkedin.md
  oss-gg/4-starry-eyed-supporter.md
  oss-gg/5-follow-twitter-x.md
  oss-gg/6-secret-side-quests.md
  oss-gg/7-quest-wizard.md
  oss-gg/8-design-new-logo-papermark.md
  oss-gg/9-record-your-first-user-experience.md
Labels: 🕹️ oss.gg, 🕹️ 150 points

#650 ossgg: Add submission for record onbording
  oss-gg/9-record-your-first-user-experience.md
Labels: 🕹️ oss.gg, 🕹️ 300 points

#653 chore: update index.ts
  pages/api/links/index.ts
Labels: 🕹️ oss.gg, 🕹️ 50 points

#658 ossgg: Added my submission for record onbording
  oss-gg/9-record-your-first-user-experience.md
Labels: 🕹️ oss.gg, 🕹️ 300 points

#657 feat: Logo, X and LinkedIn follow [SIDE QUEST]
  oss-gg/3-follow-linkedin.md
  oss-gg/5-follow-twitter-x.md
  oss-gg/8-design-new-logo-papermark.md
Labels: 🕹️ oss.gg

#659 Handle Duplicate Data Room Error and Display Subscription Modal When Limit Reached
  components/datarooms/settings/duplicate-dataroom.tsx
  components/ui/card.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#665 oss.gg: Follow on X, LinkedIn and logo submission
  oss-gg/3-follow-linkedin.md
  oss-gg/5-follow-twitter-x.md
  oss-gg/8-design-new-logo-papermark.md
Labels: 🕹️ oss.gg

#673 fix dataroom delete equal name issue
  components/datarooms/add-dataroom-modal.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#682 Handled error on /documents page if there is error fetching documents from server
  pages/documents/index.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#681 oss.gg:no-code side quest
  oss-gg/1-meme-magic.md
  oss-gg/2-gif-magic.md
  oss-gg/3-follow-linkedin.md
  oss-gg/5-follow-twitter-x.md
  oss-gg/8-design-new-logo-papermark.md
Labels: 🕹️ oss.gg

#683 Fix : #679
  components/upload-zone.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#686 Fixes Upload Zone UI
  components/upload-zone.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#693 fix: remove black color for subheading in dataroom groups page
  pages/datarooms/[id]/groups/index.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#700 HotFix-Dataroom-name-trim
  components/datarooms/add-dataroom-modal.tsx
  pages/api/teams/[teamId]/datarooms/[id]/index.ts
  pages/datarooms/[id]/settings/index.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#706 oss.gg:no-code-side-quest
  oss-gg/1-meme-magic.md
  oss-gg/2-gif-magic.md
  oss-gg/3-follow-linkedin.md
  oss-gg/5-follow-twitter-x.md
  oss-gg/8-design-new-logo-papermark.md
Labels: 🕹️ oss.gg, ossgg-logo, ossgg-meme, ossgg-gif

#705 Update Node.js version requirement to >= 18.17.0 in README
  README.md
Labels: 🕹️ oss.gg, 🕹️ 50 points, hacktoberfest

#709 fix: inconsistent theme in 404 screen
  pages/404.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#710 First user experience SideQuests
  oss-gg/9-record-your-first-user-experience.md
Labels: 🕹️ oss.gg, 🕹️ 300 points, oss-video

#724 Added Script for Prisma
  README.md
  package.json
Labels: 🕹️ oss.gg, :joystick: 150 points

#674 feat: make agreement name customizable
  components/links/link-sheet/agreement-panel/index.tsx
  components/view/access-form/agreement-section.tsx
  components/view/access-form/index.tsx
  components/view/dataroom/dataroom-view.tsx
  components/view/document-view.tsx
Labels: 🕹️ oss.gg, 🕹️ 750 points, hacktoberfest

#713 fix: Single State for Button Disable and Loading
  app/(auth)/login/page.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points

#718 feat: added last_used in login page
  app/(auth)/login/page.tsx
  components/hooks/useLastUsed.tsx
  lib/webstorage.ts
Labels: 🕹️ oss.gg, 🕹️ 300 points, hacktoberfest

#754 fix: add proper spacing to add-document-button
  pages/documents/index.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#802 chore:add missing PostgreSQL link
  README.md
Labels: 🕹️ oss.gg

#678 Improve document 📄 "Action" tab
  components/datarooms/add-dataroom-modal.tsx
  components/datarooms/dataroom-trial-modal.tsx
  components/datarooms/settings/duplicate-dataroom.tsx
  components/documents/add-document-modal.tsx
  components/documents/document-card.tsx
  components/documents/document-header.tsx
Labels: 🕹️ oss.gg

#789 fix: added all supported extensions in the file uploads
  components/document-upload.tsx
  components/upload-zone.tsx
Labels: 🕹️ oss.gg, 🕹️ 150 points, hacktoberfest

#855 fix: disabled to create links & duplicate documents due to free version limit
  components/documents/document-card.tsx
  components/links/links-table.tsx
Labels: 🕹️ oss.gg, 🕹️ 150 points, hacktoberfest

#870 fix: The Papermark logo on the top left on the sidebar should redirect to /documents when clicked
  components/Sidebar.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points

#806 Feat: papermark logo redirect to /document
  components/Sidebar.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points

#928 Fix - login page should always be in light theme
  app/(auth)/login/page.tsx
Labels: 🕹️ oss.gg, 🕹️ 50 points, hacktoberfest, ossgg-accepted

#950 replace word "brick" with "paper" in meme magic list
  oss-gg/1-meme-magic.md
Labels: 🕹️ oss.gg

#968 fix: Keep state in dataroom view between document and dataroom view #783
  components/datarooms/folders/view-tree.tsx
  components/view/DataroomViewer.tsx
  components/view/dataroom/dataroom-view.tsx
Labels: 🕹️ oss.gg, 🕹️ 750 points

#998 replace "Brick" with "papermark" in gif list
  oss-gg/2-gif-magic.md
Labels: 🕹️ oss.gg

#840 Feat: Added feature Export Visits to download the csv of Visits and Views
  components/documents/document-header.tsx
  pages/api/teams/[teamId]/documents/[id]/export-visits.ts
Labels: 🕹️ oss.gg, 🕹️ 750 points

#997 feat: Add "report" button to document viewer to report abuse
  components/NotionPage.tsx
  components/ui/radio-group.tsx
  components/ui/tooltip.tsx
  components/view/PDFViewer.tsx
  components/view/PagesViewer.tsx
  components/view/PagesViewerNew.tsx
  components/view/nav.tsx
  components/view/report-form.tsx
  components/view/viewer/advanced-excel-viewer.tsx
  components/view/viewer/excel-viewer.tsx
  components/view/viewer/image-viewer.tsx
  lib/webstorage.ts
  package-lock.json
  package.json
  pages/api/report.ts
Labels: 🕹️ oss.gg, 🕹️ 750 points, hacktoberfest

#823 fix: the unscrollability across the /settings/branding page across navbar-and-frontpage
  pages/settings/branding.tsx
Labels: 🕹️ oss.gg, 🕹️ 150 points

#824 Improve Loading Performance and UI in dark mode
  components/billing/upgrade-plan-modal.tsx
  pages/settings/upgrade.tsx
Labels: revisit, 🕹️ oss.gg, :joystick: 150 points

#845 fixed: added responsiveness to button for better visualization
  pages/settings/people.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#945 [Fix]:Added Overflow-auto and Gap for team members details
  pages/settings/people.tsx
Labels: 🕹️ oss.gg, 🕹️ 50 points

#1066 fixes #938 adds scrollbar to add folder modal
  components/datarooms/move-dataroom-folder-modal.tsx
  components/documents/move-folder-modal.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points

#1141 Fix Typos and Improve Clarity in Documentation
  README.md
Labels: 🕹️ oss.gg, 🕹️ 50 points

#1144 fix: Upgrade button dark mode visibility
  components/billing/upgrade-plan-modal.tsx
  pages/settings/upgrade.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points

#952 951-View dataroom folder tree list and documnet list ui fix
  components/view/DataroomViewer.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#1155 fix: resolve margin issues in DocumentList and Tree components
  components/documents/documents-list.tsx
  components/ui/nextra-filetree.tsx
  pages/documents/index.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points

#1164 1163 Fix delete team and group issue
  components/datarooms/groups/add-group-modal.tsx
  components/teams/add-team-modal.tsx
  pages/datarooms/[id]/groups/[groupId]/index.tsx
  pages/settings/general.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest

#1185 fix: truncate long file names for better ui display
  components/document-upload.tsx
Labels: 🕹️ oss.gg, 🕹️ 50 points, hacktoberfest

#1097 fix: pass theme option as url params
  components/NotionPage.tsx
  components/view/dataroom/dataroom-view.tsx
  components/view/document-view.tsx
  components/view/view-data.tsx
  lib/types.ts
  pages/api/views-dataroom.ts
  pages/view/[linkId]/index.tsx
  pages/view/domains/[domain]/[slug]/index.tsx
Labels: revisit, 🕹️ oss.gg, :joystick: 150 points, hacktoberfest, iteration-2

#1252 #1229 Add help / info tips to link settings
  components/billing/plan-badge.tsx
  components/documents/document-header.tsx
  components/links/link-sheet/agreement-section.tsx
  components/links/link-sheet/allow-download-section.tsx
  components/links/link-sheet/allow-list-section.tsx
  components/links/link-sheet/allow-notification-section.tsx
  components/links/link-sheet/deny-list-section.tsx
  components/links/link-sheet/email-authentication-section.tsx
  components/links/link-sheet/email-protection-section.tsx
  components/links/link-sheet/expiration-section.tsx
  components/links/link-sheet/feedback-section.tsx
  components/links/link-sheet/link-item.tsx
  components/links/link-sheet/og-section.tsx
  components/links/link-sheet/password-section.tsx
  components/links/link-sheet/question-section.tsx
  components/links/link-sheet/screenshot-protection-section.tsx
  components/links/link-sheet/watermark-section.tsx
  components/ui/tooltip.tsx
  pages/settings/branding.tsx
  pages/settings/domains.tsx
  pages/settings/presets.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points, hacktoberfest

#1260 Fixed hover issue in create link
  components/links/link-sheet/question-section.tsx
Labels: 🕹️ oss.gg, 🕹️ 50 points, hacktoberfest, player submission

#1258 add doc one dataroom to second
  components/datarooms/dataroom-document-card.tsx
  components/documents/add-document-to-dataroom-modal.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points, hacktoberfest

#1267 Add dataroom folder to other dataroom
  components/documents/add-folder-to-dataroom-modal.tsx
  components/documents/folder-card.tsx
  pages/api/teams/[teamId]/datarooms/[id]/folders/manage/[folderId]/dataroom-to-dataroom.ts
Labels: 🕹️ oss.gg, hacktoberfest, player submission

#1273 feat: add additional sorting options for documents
  components/documents/filters/sort-button.tsx
  components/search-box.tsx
  pages/api/teams/[teamId]/documents/index.ts
Labels: 🕹️ oss.gg, 🕹️ 300 points

#1277 Fixed create link issue
  components/welcome/dataroom-upload.tsx
  components/welcome/notion-form.tsx
  components/welcome/special-upload.tsx
  components/welcome/upload.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest, player submission

#1303 Fix DR trial link fails
  components/welcome/dataroom-upload.tsx
Labels: 🕹️ oss.gg, 🕹️ 50 points, hacktoberfest, player submission

#1316 Fix notion file upload
  components/documents/add-document-modal.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest, player submission

#1307 1046 [BUG] Link Sheet toggles hidden on mobile devices when "custom social media card toggle" active
  components/links/link-sheet/og-section.tsx
  components/links/link-sheet/watermark-panel/index.tsx
  components/links/link-sheet/watermark-section.tsx
Labels: 🕹️ oss.gg, 🕹️ 300 points, hacktoberfest

#1309 Fixed: Two scroll bars appear on small screens on almost every page
  components/layouts/app.tsx
Labels: 🕹️ oss.gg, 🕹️ 50 points, hacktoberfest, player submission

#1312 fix: added missing link in branding
  pages/datarooms/[id]/branding/index.tsx
  pages/datarooms/[id]/groups/index.tsx
  pages/settings/branding.tsx
Labels: 🕹️ oss.gg, :joystick: 150 points, hacktoberfest, player submission
